export const estados = {
 "CIUDAD_DE_MÉXICO" : "CIUDAD DE MÉXICO",
 "PUEBLA" : "PUEBLA" ,
 "MEXICO" : "MÉXICO",
 "SAN_LUIS_POTOSÍ" : "SAN LUIS POTOSÍ",
 "COAHUILA_DE_ZARAGOZA" : "COAHUILA DE ZARAGOZA",
 "HIDALGO" : "HIDALGO",
 "CHIHUAHUA" : "CHIHUAHUA",
 "MICHOACÁN_DE_OCAMPO" : "MICHOACÁN DE OCAMPO",
 "QUINTANA_ROO" : "QUINTANA ROO" ,
 "CAMPECHE" : "CAMPECHE" ,
 "CHIAPAS" : "CHIAPAS",
 "OAXACA" : "OAXACA",
 "GUERRERO" : "GUERRERO" ,
 "YUCATÁN" : "YUCATÁN" ,
 "DURANGO" : "DURANGO",
 "NUEVO_LEÓN" : "NUEVO LEÓN"
}